begin;

create table if not exists public.rembrandt_project_revisions (
  id bigint generated by default as identity primary key,
  content jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists rembrandt_project_revisions_created_at_idx
  on public.rembrandt_project_revisions (created_at desc);

alter table public.rembrandt_project_revisions enable row level security;
alter table public.rembrandt_project_revisions force row level security;

revoke all on table public.rembrandt_project_revisions from public, anon, authenticated;
grant select, insert, delete on table public.rembrandt_project_revisions to authenticated;
grant usage, select on sequence public.rembrandt_project_revisions_id_seq to authenticated;

drop policy if exists rembrandt_project_revisions_admin_read on public.rembrandt_project_revisions;
create policy rembrandt_project_revisions_admin_read
  on public.rembrandt_project_revisions for select
  to authenticated
  using ((select private.is_admin()));

drop policy if exists rembrandt_project_revisions_admin_insert on public.rembrandt_project_revisions;
create policy rembrandt_project_revisions_admin_insert
  on public.rembrandt_project_revisions for insert
  to authenticated
  with check ((select private.is_admin()));

drop policy if exists rembrandt_project_revisions_admin_delete on public.rembrandt_project_revisions;
create policy rembrandt_project_revisions_admin_delete
  on public.rembrandt_project_revisions for delete
  to authenticated
  using ((select private.is_admin()));

commit;
