--
-- DEPRECATED SECURITY NOTE
-- ------------------------
-- This file used to create unrestricted anon INSERT and SELECT policies for
-- raw telemetry. It is intentionally a no-op now: public browser access to
-- analytics is unsafe. Run 202608200001_analytics_v2_security.sql instead;
-- it removes any policies this historic migration previously installed,
-- creates a server-only v2 collector, and provides an admin aggregate API.
--
-- The comments are retained as a migration marker for projects that already
-- recorded this version. Do not reintroduce permissive raw analytics policies.
